name: Release Windows (NSIS + ZIP)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name to release (e.g., v0.1.0)'
        required: false

jobs:
  build-and-release-windows:
    name: Build and Release (Windows)
    runs-on: windows-latest
    permissions:
      contents: write  # allow creating releases and uploading assets

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (electron-builder)
        run: npm run build

      - name: Compute artifact list
        id: artifacts
        shell: pwsh
        run: |
          $files = @(
            'release/Photo-Watermark-*.exe',
            'release/Photo-Watermark-*.exe.blockmap',
            'release/latest.yml',
            'release/Photo-Watermark-*.zip'
          )
          echo "files<<EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          $files -join "\n" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          echo "EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.artifacts.outputs.files }}
          draft: false
          prerelease: false
          tag_name: ${{ inputs.tag || github.ref_name }}
          name: ${{ inputs.tag || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
